<a href="https://colab.research.google.com/github/ngohoangkha1508-hue/THDeeplearning/blob/main/THDeeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
my_list =[1,9,15,39]
print('Python list: ', my_list)
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

a= np.array([1,9,15,39])
print(a)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
[ 1  9 15 39]


In [4]:
c = np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [5]:
import numpy as np

# Bước 1: Khởi tạo mảng d với các giá trị số thực
# Mảng này có cấu trúc 3 chiều (3D Array)
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11, 12]]
])

# Bước 2: In nội dung của mảng ra màn hình
print("Nội dung của mảng d:")
print(d)

# Bước 3: Kiểm tra kích thước (hình dạng) của mảng
print("\nKích thước của mảng (d.shape):")
print(d.shape)

Nội dung của mảng d:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

Kích thước của mảng (d.shape):
(2, 2, 3)


In [6]:
import numpy as np

# 1. Tạo ma trận không (Zero matrix)
# Hàm np.zeros nhận vào một Tuple (hàng, cột)
e = np.zeros((2, 2))

# 2. Tạo ma trận đơn vị (One matrix - tất cả là số 1)
# Hàm np.ones nhận vào một Tuple (hàng, cột)
f = np.ones((3, 3))

# Hiển thị kết quả
print('Zero matrix:\n', e)
print('\nOne matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]

One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
import numpy as np

# --- PHẦN 1: Làm việc với mảng 2D ---
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print("Mảng e gốc (shape 2,3):\n", e)

# Thay đổi e từ (2 hàng, 3 cột) thành (3 hàng, 2 cột)
f = e.reshape(3, 2)
print("\nMảng f sau khi reshape(3, 2):\n", f)

# --- PHẦN 2: Làm việc với mảng 3D ---
g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print("\nMảng g gốc (shape 2,2,3):\n", g)

# Biến đổi g thành mảng 2D (3 hàng, 4 cột)
h = g.reshape(3, 4)
print("\nreshape (3, 4):\n", h)

# Biến đổi g thành mảng 3D khác (3 khối, mỗi khối 2x2)
j = g.reshape(3, 2, 2)
print("\nreshape (3, 2, 2):\n", j)

# Biến đổi g thành mảng 3D khác (2 khối, mỗi khối 3x2)
k = g.reshape(2, 3, 2)
print("\nreshape (2, 3, 2):\n", k)

Mảng e gốc (shape 2,3):
 [[1. 2. 3.]
 [4. 5. 6.]]

Mảng f sau khi reshape(3, 2):
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

Mảng g gốc (shape 2,2,3):
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

reshape (3, 4):
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

reshape (3, 2, 2):
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]

reshape (2, 3, 2):
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [8]:
import numpy as np

# Trường hợp 1: Biến mảng 2D thành mảng 1D
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print("Mảng f (phẳng từ e):")
print(f)

# Trường hợp 2: Biến mảng 3D thành mảng 1D
g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
j = g.flatten()
print("\nMảng j (phẳng từ g):")
print(j)

Mảng f (phẳng từ e):
[1. 2. 3. 4. 5. 6.]

Mảng j (phẳng từ g):
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [9]:
import numpy as np

# Khởi tạo hai mảng 1 chiều gốc
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

# 1. Ghép nối theo chiều ngang (Horizontal stack)
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)

# 2. Ghép nối theo chiều dọc (Vertical stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [10]:
a = np.random.randint(100,size=(5,))
print('Random 1-D array\n', a)
b = np.random.randint(100,size=(3,4))
print('Random 2-D array\n', b)
c = np.random.randint(100,size=(3,4,3))
print('Random 3-D array\n',c)

Random 1-D array
 [46 35 82  9 67]
Random 2-D array
 [[39 95 15 63]
 [87 11 42 68]
 [77  7  0 86]]
Random 3-D array
 [[[16  7 50]
  [18 38 63]
  [62 69 59]
  [83 32 26]]

 [[12 51 43]
  [27 52 83]
  [ 4 59 73]
  [62 66 26]]

 [[ 6 42 93]
  [94 56 21]
  [38 61 46]
  [77  0 54]]]


In [14]:
a = np.random.rand(5)
print('Random 1-D array\n', a)
b = np.random.rand(3,4)
print('Random 2_D array\n', b)
c = np.random.rand(3,4,3)
print('Random 3_D array\n', c)

Random 1-D array
 [0.83478047 0.1516746  0.18048448 0.67982263 0.80572035]
Random 2_D array
 [[0.58588215 0.61717027 0.56437192 0.35551721]
 [0.07927281 0.43979034 0.63738777 0.05674627]
 [0.80037643 0.94205407 0.67865082 0.4626454 ]]
Random 3_D array
 [[[0.37063833 0.91078422 0.17363379]
  [0.85201343 0.4851889  0.12010911]
  [0.70537291 0.53047591 0.48255666]
  [0.12285794 0.77145904 0.44469795]]

 [[0.29606266 0.62505559 0.74867971]
  [0.78385173 0.15058398 0.52253405]
  [0.44097198 0.26014483 0.1094036 ]
  [0.84006194 0.68892053 0.27797845]]

 [[0.35342145 0.34385459 0.51365433]
  [0.71466436 0.40749055 0.47210905]
  [0.37751164 0.69232851 0.25513839]
  [0.14271927 0.85549871 0.68823721]]]


In [19]:
a = np.random.normal(5,0.5,10)
print(a)

[4.6605414  5.42563999 5.97681487 5.09561778 4.34745719 5.16563704
 4.9450425  4.29292224 5.02968859 5.74773402]


In [ ]:
import numpy as np

# Danh sách các lựa chọn cho trước (các số chẵn từ 2 đến 20)
options = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

# 1. Sinh 1 giá trị ngẫu nhiên duy nhất từ mảng cho trước
a = np.random.choice(options)
print("Giá trị ngẫu nhiên a:", a)

# 2. Sinh ma trận 3x5 gồm các giá trị lấy ngẫu nhiên từ mảng cho trước
b = np.random.choice(options, size=(3, 5))
print("\nMa trận ngẫu nhiên b (3x5):\n", b)

In [20]:
import numpy as np

# Bước 1: Tạo ma trận 5x5 toàn số 1
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)

# Bước 2: Thử thay đổi giá trị hàng thứ 3 bằng np.array()
np.array(A)[2] = 2
print('\nChange values of third row with array (Không đổi):\n', A)

# Bước 3: Thử thay đổi giá trị hàng thứ 3 bằng np.asarray()
np.asarray(A)[2] = 2
print('\nChange values of third row with asarray (Có đổi):\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Change values of third row with array (Không đổi):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Change values of third row with asarray (Có đổi):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
a = np.arange(1,20)
print(a)
b = np.arange(1,20,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [23]:
a = np.linspace(1.,5.,num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
import numpy as np

# Tạo mảng 2 chiều (2 hàng, 3 cột)
a = np.array([(1, 2, 3), (4, 5, 6)])
print("Mảng gốc a:\n", a)

# --- PHẦN 1: TRUY CẬP THEO HÀNG ---
print('first row:', a[0])   # Lấy hàng index 0 (hàng 1)
print('second row:', a[1])  # Lấy hàng index 1 (hàng 2)

# --- PHẦN 2: TRUY CẬP THEO CỘT (Slicing) ---
# Cú pháp chung: a[hàng, cột]
# Dấu ":" nghĩa là "lấy tất cả"
print('Second column:', a[:, 1]) # Lấy tất cả hàng, nhưng chỉ lấy cột index 1
print('First column:', a[:, 0])  # Lấy tất cả hàng, nhưng chỉ lấy cột index 0

# --- PHẦN 3: KẾT HỢP ---
# Lấy hàng index 1, và lấy các giá trị từ đầu đến trước index 2
print('First two values of second row:', a[1, :2])


In [ ]:
import numpy as np

# Bước 1: Tạo mảng 3x3 với các số nguyên ngẫu nhiên từ 0 đến 20
# Lưu ý: Để bao gồm cả số 20, ta để giới hạn trên là 21
matrix = np.random.randint(0, 21, size=(3, 3))

print("Ma trận ngẫu nhiên:\n", matrix)

# Bước 2: Kiểm tra xem tất cả các phần tử có khác 0 hay không
# Biểu thức (matrix != 0) sẽ trả về một mảng Booleans (True/False)
check_all_nonzero = np.all(matrix != 0)

print("\nTất cả các phần tử đều khác 0?")
print(check_all_nonzero)

# Thêm một cách kiểm tra khác: Có phần tử nào bằng 0 không?
check_any_zero = np.any(matrix == 0)
print(f"\nCó phần tử nào bằng 0 không? {check_any_zero}")

In [ ]:
import numpy as np
a = np.random.randint(0, 21, size=(3, 3))
print("Mảng:\n", a)
print("Có tồn tại phần tử khác 0 không?", np.any(a != 0))

In [ ]:
x = np.array([1, 5, 10])
y = np.array([1, 2, 12])
print("Lớn hơn (x > y):", np.greater(x, y))            # [False, True, False]
print("Lớn hơn hoặc bằng:", np.greater_equal(x, y))   # [True, True, False]
print("Nhỏ hơn:", np.less(x, y))                      # [False, False, True]
print("Nhỏ hơn hoặc bằng:", np.less_equal(x, y))      # [True, False, True]

In [24]:
arr = np.concatenate([np.ones(10), np.zeros(10), np.full(10, 5)])
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [ ]:
# stop là 71 để bao gồm cả số 70
even_arr = np.arange(30, 71, 2)
print(even_arr)

In [25]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.linspace(15, 55, 10) # Tạo 10 phần tử đều nhau
print("Gốc:", a)
print("Kết quả:", a[1:-1]) # Slicing từ index 1 đến sát cuối

In [ ]:
a = np.arange(21)
# Dùng indexing điều kiện: nếu số đó >=9 và <=15 thì nhân với -1
a[(a >= 9) & (a <= 15)] *= -1
print(a)

In [ ]:
matrix_3x4 = np.random.randint(10, 22, size=(3, 4))
print(matrix_3x4)

In [ ]:
m = np.ones((10, 10))
m[1:-1, 1:-1] = 0 # Cắt phần lõi và gán bằng 0
print(m)

In [26]:
diag_matrix = np.diag([1, 2, 3, 4, 5])
print(diag_matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
diag_matrix = np.diag([1, 2, 3, 4, 5])
print(diag_matrix)

In [ ]:
m_3d = np.random.randint(1, 10, size=(3, 3, 3))
print("Tổng theo cột (axis 0):\n", np.sum(m_3d, axis=0))
print("Tổng theo dòng (axis 1):\n", np.sum(m_3d, axis=1))

In [ ]:
v1 = np.random.rand(10)
v2 = np.random.rand(10)
result = np.dot(v1, v2)
print("Inner product:", result)

In [ ]:
A = np.random.randint(1, 10, size=(4, 3))
y = np.array([10, 20, 30]) # Vector 3 phần tử
result = A + y
print("Ma trận A:\n", A)
print("Kết quả sau khi cộng y vào từng dòng:\n", result)

In [ ]:
import pandas as pd
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])
print("Cộng:\n", s1 + s2)
print("Trừ:\n", s1 - s2)
print("Nhân:\n", s1 * s2)
print("Chia:\n", s1 / s2)

In [ ]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
# Lấy cột đầu tiên (index 0)
s = df.iloc[:, 0]
print(s)

In [ ]:
df = pd.DataFrame(np.random.randint(1, 10, size=(4, 3)), columns=['C1', 'C2', 'C3'])
# Sắp xếp theo giá trị của cột 'C1'
df_sorted = df.sort_values(by='C1')
print(df_sorted)

In [ ]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
# Reindex sang danh sách mới
s_new = s.reindex(['c', 'b', 'a', 'd'])
print(s_new)

In [28]:
import pandas as pd
import numpy as np

sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

# sr1.isin(sr2) trả về True nếu phần tử sr1 nằm trong sr2
# Ta dùng dấu ~ để lấy những phần tử KHÔNG nằm trong sr2
result = sr1[~sr1.isin(sr2)]
print("Items of sr1 not present in sr2:\n", result)

Items of sr1 not present in sr2:
 0    1
2    3
4    5
dtype: int64


In [ ]:
x = np.random.randint(0, 20, 20)
y = np.random.randint(0, 20, 20)

print("Giao (Intersect):", np.intersect1d(x, y))
print("Hội (Union):", np.union1d(x, y))

In [ ]:
x = pd.Series(range(10))
y = pd.Series(['p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'])

# Chiều dọc (Vertical) - Mặc định axis=0
vertical = pd.concat([x, y], axis=0)

# Chiều ngang (Horizontal) - axis=1
horizontal = pd.concat([x, y], axis=1)

print("Dọc:\n", vertical.head(5)) # In 5 dòng đầu
print("\nNgang:\n", horizontal.head(5))

In [ ]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print(df)

In [30]:
import pandas as pd
import numpy as np

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)

# 23. 3 dòng đầu tiên
print("\n23. 3 dòng đầu:\n", df.head(3))

# 24. Chọn cột 'name' và 'score'
print("\n24. Cột name và score:\n", df[['name', 'score']])

# 25. Dòng có attempts > 2
print("\n25. Attempts > 2:\n", df[df['attempts'] > 2])

# 26. Số dòng và số cột
print(f"\n26. Kích thước (dòng, cột): {df.shape}")

# 27. Dòng có score là NaN
print("\n27. Score bị thiếu (NaN):\n", df[df['score'].isnull()])

# 28. Score trong khoảng (15, 20)
print("\n28. Score trong khoảng [15, 20]:\n", df[df['score'].between(15, 20)])

# 29. Kết hợp điều kiện (attempts > 2 AND score 15-20)
print("\n29. Kết hợp điều kiện:\n", df[(df['attempts'] > 2) & (df['score'].between(15, 20))])

# 30. Thay đổi giá trị dòng 'd', cột 'score' thành 19
df.loc['d', 'score'] = 19
print("\n30. Sau khi sửa dòng 'd':\n", df.loc[['d']])


23. 3 dòng đầu:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

24. Cột name và score:
         name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

25. Attempts > 2:
       name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

26. Kích thước (dòng, cột): (10, 4)

27. Score bị thiếu (NaN):
     name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

28. Score trong khoảng [15, 20]:
         name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

29. Kết hợp điều kiện:
       name  score  attempts qualify
f  Mic

In [ ]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

In [33]:
import pandas as pd
import numpy as np

# Tạo dữ liệu giả lập cho tệp dulieuxettuyendaihoc.csv
data = {
    'STT': range(1, 11),
    'DT': [1, np.nan, 0, 1, np.nan, 0, 1, 0, np.nan, 1],
    'KT': ['A', 'A1', 'B', 'C', 'D', 'A', 'B', 'A1', 'C', 'D'],
    'T1': np.random.uniform(5, 10, 10), 'L1': np.random.uniform(5, 10, 10), 'H1': np.random.uniform(5, 10, 10),
    'S1': np.random.uniform(5, 10, 10), 'V1': np.random.uniform(5, 10, 10), 'X1': np.random.uniform(5, 10, 10),
    'D1': np.random.uniform(5, 10, 10), 'N1': np.random.uniform(5, 10, 10),
    'T2': np.random.uniform(5, 10, 10), 'L2': np.random.uniform(5, 10, 10), 'H2': np.random.uniform(5, 10, 10),
    'S2': np.random.uniform(5, 10, 10), 'V2': np.random.uniform(5, 10, 10), 'X2': np.random.uniform(5, 10, 10),
    'D2': np.random.uniform(5, 10, 10), 'N2': np.random.uniform(5, 10, 10),
    'T6': np.random.uniform(5, 10, 10), 'L6': np.random.uniform(5, 10, 10), 'H6': np.random.uniform(5, 10, 10),
    'S6': np.random.uniform(5, 10, 10), 'V6': np.random.uniform(5, 10, 10), 'X6': np.random.uniform(5, 10, 10),
    'D6': np.random.uniform(5, 10, 10), 'N6': np.random.uniform(5, 10, 10),
    'DH1': np.random.uniform(2, 9, 10), 'DH2': np.random.uniform(2, 9, 10), 'DH3': np.random.uniform(2, 9, 10)
}

df_sample = pd.DataFrame(data)
df_sample.to_csv('dulieuxettuyendaihoc.csv', index=False)
print("Đã tạo tệp mẫu 'dulieuxettuyendaihoc.csv' thành công!")

Đã tạo tệp mẫu 'dulieuxettuyendaihoc.csv' thành công!


In [37]:
import pandas as pd
import numpy as np
import os

# --- Bước 3: Tải dữ liệu ---
file_path = 'dulieuxettuyendaihoc.csv'

if not os.path.exists(file_path):
    print(f"Lỗi: Không tìm thấy tệp '{file_path}'.")
    print("Vui lòng chạy ô mã tạo dữ liệu mẫu trước khi thực hiện bước này.")
else:
    df = pd.read_csv(file_path)

    print("10 dòng đầu tiên của dữ liệu:")
    print(df.head(10))
    print("\n10 dòng cuối cùng của dữ liệu:")
    print(df.tail(10))

    # --- Bước 4: Xử lý dữ liệu thiếu cho cột DT (Dân tộc) ---
    print("\nCác giá trị dân tộc hiện có:", df['DT'].unique())
    df['DT'] = df['DT'].fillna(0)

    # --- Bước 5 & 6: Xử lý dữ liệu thiếu cho các cột điểm số ---
    diem_cols = [
        'T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1',
        'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2',
        'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6',
        'DH1', 'DH2', 'DH3'
    ]

    for col in diem_cols:
        if col in df.columns:
            mean_val = df[col].mean()
            df[col] = df[col].fillna(mean_val)

    # --- Bước 7: Tính toán điểm trung bình môn (TBM) ---
    for i, year in enumerate(['1', '2', '6'], 1):
        tbm_col = f'TBM{i}'
        df[tbm_col] = (df[f'T{year}']*2 + df[f'L{year}'] + df[f'H{year}'] + df[f'S{year}'] +
                        df[f'V{year}']*2 + df[f'X{year}'] + df[f'D{year}'] + df[f'N{year}']) / 10

    # --- Bước 8: Xếp loại học lực (XL) ---
    def classify(score):
        if score < 5.0: return 'Y'
        elif score < 6.5: return 'TB'
        elif score < 8.0: return 'K'
        elif score < 9.0: return 'G'
        else: return 'XS'

    for i in range(1, 4):
        df[f'XL{i}'] = df[f'TBM{i}'].apply(classify)

    # --- Bước 9: Quy đổi thang điểm Mỹ (US_TBM - Thang 4) ---
    for i in range(1, 4):
        df[f'US_TBM{i}'] = (df[f'TBM{i}'] / 10) * 4

    # --- Bước 10: Kết quả xét tuyển (KQXT) ---
    def check_admission(row):
        kt = row['KT']
        dh1, dh2, dh3 = row['DH1'], row['DH2'], row['DH3']

        if kt in ['A', 'A1']:
            score = (dh1*2 + dh2 + dh3) / 4
        elif kt == 'B':
            score = (dh1 + dh2*2 + dh3) / 4
        else:
            score = (dh1 + dh2 + dh3) / 3

        return 1 if score >= 5.0 else 0

    df['KQXT'] = df.apply(check_admission, axis=1)

    # --- Bước 11: Lưu trữ file sạch ---
    df.to_csv('processed_dulieuxettuyendaihoc.csv', index=False)
    print("\n--- Xử lý hoàn tất! File 'processed_dulieuxettuyendaihoc.csv' đã được tạo. ---")

10 dòng đầu tiên của dữ liệu:
   STT   DT  KT        T1        L1        H1        S1        V1        X1  \
0    1  1.0   A  8.798453  8.645261  5.024375  5.061727  7.859913  6.879745   
1    2  NaN  A1  8.175967  5.791547  7.418877  8.389609  7.297847  5.631281   
2    3  0.0   B  8.637372  9.276761  5.960253  5.085373  6.911359  7.104586   
3    4  1.0   C  5.704555  8.455600  6.683240  6.266811  5.238749  6.890193   
4    5  NaN   D  5.476047  7.700826  5.481212  7.274654  8.047879  7.003193   
5    6  0.0   A  7.541431  6.003108  9.873552  6.306648  5.872821  6.760166   
6    7  1.0   B  9.022331  6.329302  9.157258  6.262515  9.991651  7.840885   
7    8  0.0  A1  7.656494  9.415502  5.670430  8.707855  5.856419  5.097865   
8    9  NaN   C  9.638177  6.438986  7.574575  7.344273  7.011356  9.807771   
9   10  1.0   D  8.685119  8.946455  7.990046  5.781620  6.888719  7.918587   

         D1  ...        L6        H6        S6        V6        X6        D6  \
0  8.741059  ...  6.